apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: hotel-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: kubenode-a
      containers:
      - name: review-service
        image: lyricwang/mini-service-review-service:v1
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://review-db.hotel-a:3306/reviewdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: rootpassword
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          value: http://otel-collector.istio-system.svc.cluster.local:9411/api/v2/spans
        - name: SPRING_APPLICATION_NAME
          value: review-service.hotel-a
        ports:
          - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: hotel-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: kubenode-b
      containers:
      - name: review-service
        image: lyricwang/mini-service-review-service:v1
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://review-db.hotel-a:3306/reviewdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: rootpassword
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          value: http://otel-collector.istio-system.svc.cluster.local:9411/api/v2/spans
        - name: SPRING_APPLICATION_NAME
          value: review-service.hotel-b
        ports:
          - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: hotel-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: kubenode-c
      containers:
      - name: review-service
        image: lyricwang/mini-service-review-service:v1
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://review-db.hotel-a:3306/reviewdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: rootpassword
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          value: http://otel-collector.istio-system.svc.cluster.local:9411/api/v2/spans
        - name: SPRING_APPLICATION_NAME
          value: review-service.hotel-c
        ports:
          - containerPort: 8080