apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: hotel-a
spec:
  selector:
    app: review-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: hotel-b
spec:
  selector:
    app: review-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: hotel-c
spec:
  selector:
    app: review-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort