apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: hotel
spec:
  selector:
    app: review-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30082
  type: NodePort  