apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: review-db
  namespace: hotel-a
  labels:
    app: review-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-db
  template:
    metadata:
      labels:
        app: review-db
    spec:
      containers:
      - name: review-db
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: reviewdb
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: review-db-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: review-db-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: review-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/review-db-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubenode-a