apiVersion: v1
kind: Service
metadata:
  name: review-db
spec:
  selector:
    app: review-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 3308
  type: NodePort