apiVersion: v1
kind: Service
metadata:
  name: review-db
  namespace: hotel
  labels:
    app: review-db
spec:
  selector:
    app: review-db
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30308
  type: NodePort