apiVersion: v1
kind: Service
metadata:
  name: review-db
  namespace: hotel-a
  labels:
    app: review-db
spec:
  selector:
    app: review-db
  ports:
    - port: 3306
      targetPort: 3306
  type: NodePort