apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calendar-db
  namespace: hotel
  labels:
    app: calendar-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-db
  template:
    metadata:
      labels:
        app: calendar-db
    spec:
      containers:
      - name: calendar-db
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: calendardb
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: calendar-db-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: calendar-db-data
    spec:
      accessModes: ["ReadWriteOnce"]
      volumeName: calendar-db-pv
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calendar-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/calendar-db-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubenode-b