apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: istio-system
  labels:
    app: otel-collector
data:
  otel-collector-config: |
    receivers:
      zipkin:
        endpoint: "0.0.0.0:9411"

    processors:
      batch:
        timeout: 5s
        send_batch_size: 10

    exporters:
      elasticsearch:
        endpoints: ["https://my-elasticsearch-es-internal-http.istio-system:9200"] 
        index: "otel-traces"
        auth:
          authenticator: basicauth
        tls:
          insecure_skip_verify: true
      zipkin: # Zipkin for visualization
        endpoint: "http://zipkin.istio-system:9411/api/v2/spans"
    extensions:
      basicauth:
        client_auth:
          username: "elastic"
          password: "${ELASTIC_PASSWORD}"
    service:
      extensions: [basicauth]
      pipelines:
        traces:
          receivers: [zipkin]
          processors: [batch]
          exporters: [elasticsearch, zipkin]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: istio-system
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      nodeSelector:
        kubernetes.io/hostname: kubenode-a
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:latest
          args: ["--config=/conf/otel-collector-config.yaml"]
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /conf/otel-collector-config.yaml
              subPath: otel-collector-config
          ports:
            - containerPort: 9411  # Zipkin 端口
            - containerPort: 14250 # Jaeger gRPC 端口
            - containerPort: 9200  # Elasticsearch HTTP 端口
          env:
            - name: ELASTIC_PASSWORD  # 环境变量名
              valueFrom:
                secretKeyRef:
                  name: my-elasticsearch-es-elastic-user  # Secret 名称
                  key: elastic  # Secret 中的字段名
      volumes:
        - name: otel-collector-config-vol
          configMap:
            name: otel-collector-conf
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: istio-system
  labels:
    app: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - name: zipkin
      protocol: TCP
      port: 9411
      targetPort: 9411  # Zipkin 接收器端口
    - name: jaeger-grpc
      protocol: TCP
      port: 14250
      targetPort: 14250  # Jaeger gRPC 接收端口
    - name: jaeger-http
      protocol: TCP
      port: 14268
      targetPort: 14268  # Jaeger HTTP 接收端口
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317  # OTLP gRPC 接收端口
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318  # OTLP HTTP 接收端口