apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: listing-db
  namespace: hotel-b
  labels:
    app: listing-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listing-db
  template:
    metadata:
      labels:
        app: listing-db
    spec:
      containers:
      - name: listing-db
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: listingdb
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: listing-db-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: listing-db-data
    spec:
      volumeName: listing-db-pv
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: listing-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/listing-db-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubenode-b