apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-service
  namespace: hotel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listing-service
  template:
    metadata:
      labels:
        app: listing-service
    spec:
      containers:
      - name: listing-service
        image: lyricwang/mini-service-listing-service:v1
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://listing-db:3306/listingdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: rootpassword
        ports:
          - containerPort: 8080