apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnode-a
spec:
  capacity:
    storage: 10Gi
  storageClassName: az1
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubenode-a
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnode-b
spec:
  capacity:
    storage: 10Gi
  storageClassName: az2
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubenode-b
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnode-c
spec:
  capacity:
    storage: 10Gi
  storageClassName: az3
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubenode-c