apiVersion: v1
kind: Service
metadata:
  name: calendar-service
  namespace: hotel-a
spec:
  selector:
    app: calendar-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-service
  namespace: hotel-b
spec:
  selector:
    app: calendar-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-service
  namespace: hotel-c
spec:
  selector:
    app: calendar-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080